service: korper-backend
frameworkVersion: '3'

provider:
  iam:
    role: DefaultRole
  httpApi:
    cors: true
    authorizers:
      korperAuthorizer:
        type: request
        functionName: auth_authorizer
        identitySource:   
          - $request.header.Authorization
        enableSimpleResponses: true
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: dev
  environment:
    STAGE: ${env:STAGE, "dev"}
    JWT_SECRET_KEY: ${ssm:/${self:service}/${env:STAGE, "dev"}/jwt_secret_key}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    external:
      ['@sparticuz/chromium-min', 'pg', 'pg-query-stream', 'sqlite3', 'better-sqlite3', 'oracledb', 'tedious', 'mysql']

plugins:
  - serverless-esbuild

resources:
  Resources:
    DefaultRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${env:STAGE, "dev"}-LambdaExcutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - rds-db:connect
                    - logs:*
                    - athena:*
                    - ssm:*
                    - execute-api:*
                    - secretsmanager:*
                    - lambda:*
                    - sns:*
                    - sqs:*
                  Resource: '*'

functions:
  hello:
    handler: build/hello/get.handler
    events:
      - httpApi:
          path: /hello
          method: get
  auth_authorizer:
    handler: build/auth/authorizer.handler
    events: []
  api_docs_get:
    handler: build/api/docs/get.handler
    events:
      - httpApi:
          path: /api/docs
          method: get
    package:
      include:
        - apiDocs.yml
  signin_apple_post:
    handler: build/signin/apple/post.handler
    events:
      - httpApi:
          path: /signin/apple
          method: post
  signin_naver_post:
    handler: build/signin/naver/post.handler
    events:
      - httpApi:
          path: /signin/naver
          method: post
  signin_kakao_post:
    handler: build/signin/kakao/post.handler
    events:
      - httpApi:
          path: /signin/kakao
          method: post
  signin_google_post:
    handler: build/signin/google/post.handler
    events:
      - httpApi:
          path: /signin/google
          method: post
  token_access_get:
    handler: build/token/access/get.handler
    events:
      - httpApi:
          path: /token/access
          method: get
  token_refresh_delete:
    handler: build/token/refresh/delete.handler
    events:
      - httpApi:
          path: /token/refresh
          method: delete
          authorizer:
            name: korperAuthorizer
  user_get:
    handler: build/user/get.handler
    events:
      - httpApi:
          path: /user
          method: get
          authorizer: 
            name: korperAuthorizer
  user_put:
    handler: build/user/put.handler
    events:
      - httpApi:
          path: /user
          method: put
          authorizer: 
            name: korperAuthorizer
